apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-16
  namespace: ns16
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      type: fast-16
