---
apiVersion: v1
kind: Service
metadata:
  name: py-service-16
  namespace: ns16
spec:
  type: NodePort
  selector:
    app: python-app-16
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30116